sudo: required
dist: trusty
language: cpp
compiler:
    - clang
    - gcc
env:
    global:
        - CXXFLAGS="-Wall -Wextra -Werror"
before_install:
    - sudo apt-get update -q
    - sudo apt-get install -qy qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev
script:
    - cmake .
    - make -j3 $TARGET
notifications:
    irc:
        on_success: change
        on_failure: change
        channels:
            - "chat.freenode.net#dwarftherapist"
        use_notice: true
